export type UserRole = 'SuperAdmin' | 'Administrador' | 'Gestor de Área';

export interface User {
  id: string;
  username: string;
  name: string;
  role: UserRole;
  area: string;
  pass: string;
}

export interface Supplier {
  id: string;
  nit: string;
  name: string;
  contact: string;
  phone: string;
  monthlyCount: number;
  areas: string[];
}

export interface Invoice {
  id: string;
  monthYear: string;
  supplierName: string;
  type: 'INVOICE' | 'QUOTATION';
  area: string;
  description: string;
  invoiceCode: string;
  factureReceived: 'SÍ' | 'NO';
  invoiceSigned: boolean;
  management: boolean;
  remissionDate: string;
  deliveredDate: string | null;
  amount: number;
  delivered: boolean;
  isAutoGenerated?: boolean;
}

export interface DashboardStats {
  totalCount: number;
  managedCount: number;
  toSignCount: number;
  pendingCount: number;
  deliveredCount: number;
}
